name: Byggmester Martha, klart vi kan

on: push

jobs:
  build_firmware:
    runs-on: [self-hosted, windows]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build ByggmesterMartha in AtmelStudio
      run: |
        "C:\Program Files (x86)\Atmel\Studio\7.0\AtmelStudio.exe" ByggmesterMartha/ByggmesterMartha.atsln /build debug /out buildlog.txt
